/*
 * JS for Board generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '8700fb82-4281-4205-b2b0-709172fa6b23';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "Login_banco",
    "location": "Login_banco.html"
}, {
    "name": "Login_dci",
    "location": "Login_dci.html"
}, {
    "name": "AddSell",
    "location": "AddSell.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "Login_vendedor",
    "location": "Login_vendedor.html"
}, {
    "name": "Login_corredor",
    "location": "Login_corredor.html"
}, {
    "name": "Board",
    "location": "Board.html"
}, {
    "name": "Register",
    "location": "Register.html"
}, {
    "name": "Comprador",
    "location": "Comprador.html"
}, {
    "name": "Vendedor_detalle_registro",
    "location": "Vendedor_detalle_registro.html"
}, {
    "name": "Validaciones",
    "location": "Validaciones.html"
}, {
    "name": "Login_comprador",
    "location": "Login_comprador.html"
}, {
    "name": "Vendedor",
    "location": "Vendedor.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Welcome_OAuth_Login_with_Google_App",
    "location": "Welcome_OAuth_Login_with_Google_App.html"
}, {
    "name": "Welcome",
    "location": "Welcome.html"
}, {
    "name": "VendedorViejo",
    "location": "VendedorViejo.html"
}, {
    "name": "VendedorAdjustes",
    "location": "VendedorAdjustes.html"
}];

function Board_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'userInfoList': 'Board_userInfoList',
        'mobilelistitem_5': 'Board_mobilelistitem_5',
        'mobilelistitembutton_6': 'Board_mobilelistitembutton_6',
        'mobilelistitem_7': 'Board_mobilelistitem_7',
        'mobilelistitembutton_8': 'Board_mobilelistitembutton_8'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["Board_Board_onpageshow_mapping_0"] = {
        "homeScreen": "Board",
        "directions": [
            {
                "from_name": "currentUser",
                "from_type": "LOCAL_STORAGE",
                "to_name": "Board",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['email']",
                        "target": "$['mobilelistitem_5:text']"
                    },
                    {
                        "source": "$['country']",
                        "target": "$['mobilelistitem_7:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Board';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Board_onLoad = function() {
        Board_elementsExtraJS();
        Board_deviceEvents();
        Board_windowEvents();
        Board_elementsEvents();
    };
    // screen window events
    function Board_windowEvents() {
        $('#Board').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#Board').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["Board_Board_onpageshow_mapping_0"]);
                Apperyio("userInfoList").show();
            },
        });
    };
    // device events
    function Board_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Board_elementsExtraJS() {
        // screen (Board) extra code
        /* userInfoList */
        listView = $("#Board_userInfoList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Board_userInfoList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_5 */
        /* mobilelistitem_7 */
    };
    // screen elements handler
    function Board_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#Board").on("pagebeforeshow", "#Board", function(event, ui) {
        Apperyio.CurrentScreen = "Board";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Board_onLoad();
};
$(document).off("pagecreate", "#Board").on("pagecreate", "#Board", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Board_js();
});