/*
 * JS for Comprador generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '8700fb82-4281-4205-b2b0-709172fa6b23';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "Login_banco",
    "location": "Login_banco.html"
}, {
    "name": "Login_dci",
    "location": "Login_dci.html"
}, {
    "name": "AddSell",
    "location": "AddSell.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "Login_vendedor",
    "location": "Login_vendedor.html"
}, {
    "name": "Login_corredor",
    "location": "Login_corredor.html"
}, {
    "name": "Board",
    "location": "Board.html"
}, {
    "name": "Register",
    "location": "Register.html"
}, {
    "name": "Comprador",
    "location": "Comprador.html"
}, {
    "name": "Vendedor_detalle_registro",
    "location": "Vendedor_detalle_registro.html"
}, {
    "name": "Validaciones",
    "location": "Validaciones.html"
}, {
    "name": "Login_comprador",
    "location": "Login_comprador.html"
}, {
    "name": "Vendedor",
    "location": "Vendedor.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Welcome_OAuth_Login_with_Google_App",
    "location": "Welcome_OAuth_Login_with_Google_App.html"
}, {
    "name": "Welcome",
    "location": "Welcome.html"
}, {
    "name": "VendedorViejo",
    "location": "VendedorViejo.html"
}, {
    "name": "VendedorAdjustes",
    "location": "VendedorAdjustes.html"
}];

function Comprador_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_10': 'Comprador_mobilelabel_10',
        'mobilelist_11': 'Comprador_mobilelist_11',
        'mobilelistitem_12': 'Comprador_mobilelistitem_12',
        'mobilelistitembutton_13': 'Comprador_mobilelistitembutton_13',
        'mobilelistitem_14': 'Comprador_mobilelistitem_14',
        'mobilelistitembutton_15': 'Comprador_mobilelistitembutton_15',
        'mobilelistitem_16': 'Comprador_mobilelistitem_16',
        'mobilelistitembutton_17': 'Comprador_mobilelistitembutton_17',
        'mobilelistitem_109': 'Comprador_mobilelistitem_109',
        'mobilelistitembutton_110': 'Comprador_mobilelistitembutton_110',
        'mobilebutton_111': 'Comprador_mobilebutton_111',
        'mobilenavbar_6': 'Comprador_mobilenavbar_6',
        'v1': 'Comprador_v1',
        'v2': 'Comprador_v2',
        'v3': 'Comprador_v3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Comprador';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Comprador_onLoad = function() {
        Comprador_elementsExtraJS();
        Comprador_deviceEvents();
        Comprador_windowEvents();
        Comprador_elementsEvents();
    };
    // screen window events
    function Comprador_windowEvents() {
        $('#Comprador').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Comprador_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Comprador_elementsExtraJS() {
        // screen (Comprador) extra code
        /* mobilelist_11 */
        listView = $("#Comprador_mobilelist_11");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Comprador_mobilelist_11 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_12 */
        /* mobilelistitem_14 */
        /* mobilelistitem_16 */
        /* mobilelistitem_109 */
    };
    // screen elements handler
    function Comprador_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Comprador_mobilecontainer [name="mobilelistitem_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('VendedorAdjustes', {
                        reverse: false
                    });
                }
            },
        }, '#Comprador_mobilecontainer [name="mobilelistitem_12"]');
        $(document).off("click", '#Comprador_mobilecontainer [name="mobilelistitem_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('VendedorAdjustes', {
                        reverse: false
                    });
                }
            },
        }, '#Comprador_mobilecontainer [name="mobilelistitem_14"]');
        $(document).off("click", '#Comprador_mobilefooter [name="v2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('VendedorViejo', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#Comprador_mobilefooter [name="v2"]');
        $(document).off("click", '#Comprador_mobilefooter [name="v3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('VendedorAdjustes', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#Comprador_mobilefooter [name="v3"]');
    };
    $(document).off("pagebeforeshow", "#Comprador").on("pagebeforeshow", "#Comprador", function(event, ui) {
        Apperyio.CurrentScreen = "Comprador";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Comprador_onLoad();
};
$(document).off("pagecreate", "#Comprador").on("pagecreate", "#Comprador", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Comprador_js();
});