/*
 * JS for details generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '8700fb82-4281-4205-b2b0-709172fa6b23';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "Login_banco",
    "location": "Login_banco.html"
}, {
    "name": "Login_dci",
    "location": "Login_dci.html"
}, {
    "name": "AddSell",
    "location": "AddSell.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "Login_vendedor",
    "location": "Login_vendedor.html"
}, {
    "name": "Login_corredor",
    "location": "Login_corredor.html"
}, {
    "name": "Board",
    "location": "Board.html"
}, {
    "name": "Register",
    "location": "Register.html"
}, {
    "name": "Comprador",
    "location": "Comprador.html"
}, {
    "name": "Vendedor_detalle_registro",
    "location": "Vendedor_detalle_registro.html"
}, {
    "name": "Validaciones",
    "location": "Validaciones.html"
}, {
    "name": "Login_comprador",
    "location": "Login_comprador.html"
}, {
    "name": "Vendedor",
    "location": "Vendedor.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Welcome_OAuth_Login_with_Google_App",
    "location": "Welcome_OAuth_Login_with_Google_App.html"
}, {
    "name": "Welcome",
    "location": "Welcome.html"
}, {
    "name": "VendedorViejo",
    "location": "VendedorViejo.html"
}, {
    "name": "VendedorAdjustes",
    "location": "VendedorAdjustes.html"
}];

function details_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'list': 'details_list',
        'productName': 'details_productName',
        'mobilelistitembutton_4': 'details_mobilelistitembutton_4',
        'productQuantity': 'details_productQuantity',
        'mobilelistitembutton_6': 'details_mobilelistitembutton_6',
        'productDescription': 'details_productDescription',
        'mobilelistitembutton_8': 'details_mobilelistitembutton_8'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["details_details_onpageshow_mapping_0"] = {
        "homeScreen": "details",
        "directions": [
            {
                "from_name": "selectedProduct",
                "from_type": "LOCAL_STORAGE",
                "to_name": "details",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['name']",
                        "target": "$['productName:text']"
                    },
                    {
                        "source": "$['quantity']",
                        "target": "$['productQuantity:text']"
                    },
                    {
                        "source": "$['description']",
                        "target": "$['productDescription:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'details';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var details_onLoad = function() {
        details_elementsExtraJS();
        details_deviceEvents();
        details_windowEvents();
        details_elementsEvents();
    };
    // screen window events
    function details_windowEvents() {
        $('#details').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#details').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["details_details_onpageshow_mapping_0"]);
                Apperyio("list").show();
            },
        });
    };
    // device events
    function details_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function details_elementsExtraJS() {
        // screen (details) extra code
        /* list */
        listView = $("#details_list");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#details_list .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* productName */
        /* productQuantity */
        /* productDescription */
    };
    // screen elements handler
    function details_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#details").on("pagebeforeshow", "#details", function(event, ui) {
        Apperyio.CurrentScreen = "details";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    details_onLoad();
};
$(document).off("pagecreate", "#details").on("pagecreate", "#details", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    details_js();
});