/*
 * JS for startScreen generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '8700fb82-4281-4205-b2b0-709172fa6b23';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "Login_banco",
    "location": "Login_banco.html"
}, {
    "name": "Login_dci",
    "location": "Login_dci.html"
}, {
    "name": "AddSell",
    "location": "AddSell.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "Login_vendedor",
    "location": "Login_vendedor.html"
}, {
    "name": "Login_corredor",
    "location": "Login_corredor.html"
}, {
    "name": "Board",
    "location": "Board.html"
}, {
    "name": "Register",
    "location": "Register.html"
}, {
    "name": "Comprador",
    "location": "Comprador.html"
}, {
    "name": "Vendedor_detalle_registro",
    "location": "Vendedor_detalle_registro.html"
}, {
    "name": "Validaciones",
    "location": "Validaciones.html"
}, {
    "name": "Login_comprador",
    "location": "Login_comprador.html"
}, {
    "name": "Vendedor",
    "location": "Vendedor.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Welcome_OAuth_Login_with_Google_App",
    "location": "Welcome_OAuth_Login_with_Google_App.html"
}, {
    "name": "Welcome",
    "location": "Welcome.html"
}, {
    "name": "VendedorViejo",
    "location": "VendedorViejo.html"
}, {
    "name": "VendedorAdjustes",
    "location": "VendedorAdjustes.html"
}];

function startScreen_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_22': 'startScreen_mobileimage_22',
        'mobilelabel_18': 'startScreen_mobilelabel_18',
        'mobilelabel_107': 'startScreen_mobilelabel_107',
        'mobilelist_93': 'startScreen_mobilelist_93',
        'mobilelistitem_94': 'startScreen_mobilelistitem_94',
        'mobilelabel_109': 'startScreen_mobilelabel_109',
        'mobilelistitembutton_95': 'startScreen_mobilelistitembutton_95',
        'mobilelabel_110': 'startScreen_mobilelabel_110',
        'mobilelabel_108': 'startScreen_mobilelabel_108',
        'mobilelistitem_96': 'startScreen_mobilelistitem_96',
        'mobilelistitembutton_97': 'startScreen_mobilelistitembutton_97',
        'mobilelistitem_98': 'startScreen_mobilelistitem_98',
        'mobilelistitembutton_99': 'startScreen_mobilelistitembutton_99',
        'mobilelistitem_100': 'startScreen_mobilelistitem_100',
        'mobilelistitembutton_101': 'startScreen_mobilelistitembutton_101',
        'mobilelistitem_102': 'startScreen_mobilelistitem_102',
        'mobilelistitembutton_103': 'startScreen_mobilelistitembutton_103',
        'mobilelistitem_104': 'startScreen_mobilelistitem_104',
        'mobilelistitembutton_105': 'startScreen_mobilelistitembutton_105'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["startScreen_restservice1_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };
    Apperyio.mappings["startScreen_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen",
                "from_type": "UI",
                "to_name": "productList",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['mobilelabel_18:text']",
                        "target": "$[0]['name']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(AccionesVentas_ListVentas_ventas_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_restservice1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_restservice1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var startScreen_onLoad = function() {
        startScreen_elementsExtraJS();
        startScreen_deviceEvents();
        startScreen_windowEvents();
        startScreen_elementsEvents();
    };
    // screen window events
    function startScreen_windowEvents() {
        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code
        /* mobilelist_93 */
        listView = $("#startScreen_mobilelist_93");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_mobilelist_93 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_94 */
        /* mobilelistitem_96 */
        /* mobilelistitem_98 */
        /* mobilelistitem_100 */
        /* mobilelistitem_102 */
        /* mobilelistitem_104 */
    };
    // screen elements handler
    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    startScreen_onLoad();
};
$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});