/*
 * JS for Vendedor_detalle_registro generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '8700fb82-4281-4205-b2b0-709172fa6b23';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "Login_banco",
    "location": "Login_banco.html"
}, {
    "name": "Login_dci",
    "location": "Login_dci.html"
}, {
    "name": "AddSell",
    "location": "AddSell.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "Login_vendedor",
    "location": "Login_vendedor.html"
}, {
    "name": "Login_corredor",
    "location": "Login_corredor.html"
}, {
    "name": "Board",
    "location": "Board.html"
}, {
    "name": "Register",
    "location": "Register.html"
}, {
    "name": "Comprador",
    "location": "Comprador.html"
}, {
    "name": "Vendedor_detalle_registro",
    "location": "Vendedor_detalle_registro.html"
}, {
    "name": "Validaciones",
    "location": "Validaciones.html"
}, {
    "name": "Login_comprador",
    "location": "Login_comprador.html"
}, {
    "name": "Vendedor",
    "location": "Vendedor.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Welcome_OAuth_Login_with_Google_App",
    "location": "Welcome_OAuth_Login_with_Google_App.html"
}, {
    "name": "Welcome",
    "location": "Welcome.html"
}, {
    "name": "VendedorViejo",
    "location": "VendedorViejo.html"
}, {
    "name": "VendedorAdjustes",
    "location": "VendedorAdjustes.html"
}];

function Vendedor_detalle_registro_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_10': 'Vendedor_detalle_registro_mobilelabel_10',
        'mobilelabel_115': 'Vendedor_detalle_registro_mobilelabel_115',
        'mobiletextinput_114': 'Vendedor_detalle_registro_mobiletextinput_114',
        'mobilelabel_116': 'Vendedor_detalle_registro_mobilelabel_116',
        'mobiletextinput_117': 'Vendedor_detalle_registro_mobiletextinput_117',
        'mobilelabel_118': 'Vendedor_detalle_registro_mobilelabel_118',
        'mobiletextinput_119': 'Vendedor_detalle_registro_mobiletextinput_119',
        'mobilelabel_120': 'Vendedor_detalle_registro_mobilelabel_120',
        'mobiletextinput_121': 'Vendedor_detalle_registro_mobiletextinput_121',
        'mobilecheckboxgroup_133': 'Vendedor_detalle_registro_mobilecheckboxgroup_133',
        'mobilecheckbox_135': 'Vendedor_detalle_registro_mobilecheckbox_135',
        'mobilebutton_122': 'Vendedor_detalle_registro_mobilebutton_122'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Vendedor_detalle_registro';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Vendedor_detalle_registro_onLoad = function() {
        Vendedor_detalle_registro_elementsExtraJS();
        Vendedor_detalle_registro_deviceEvents();
        Vendedor_detalle_registro_windowEvents();
        Vendedor_detalle_registro_elementsEvents();
    };
    // screen window events
    function Vendedor_detalle_registro_windowEvents() {
        $('#Vendedor_detalle_registro').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Vendedor_detalle_registro_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Vendedor_detalle_registro_elementsExtraJS() {
        // screen (Vendedor_detalle_registro) extra code
    };
    // screen elements handler
    function Vendedor_detalle_registro_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#Vendedor_detalle_registro").on("pagebeforeshow", "#Vendedor_detalle_registro", function(event, ui) {
        Apperyio.CurrentScreen = "Vendedor_detalle_registro";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Vendedor_detalle_registro_onLoad();
};
$(document).off("pagecreate", "#Vendedor_detalle_registro").on("pagecreate", "#Vendedor_detalle_registro", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Vendedor_detalle_registro_js();
});